POST http://localhost:8080/exercises/add
Accept: application/json
Content-Type: application/json

{
  "name": "Martwy ciąg",
  "engName": "abc",
  "mainMuscleGroup": [
    "abc"
  ],
  "supportMuscleGroup": [
    "abc",
    "abc"
  ]
}

###
GET http://localhost:8080/exercises

###
GET http://localhost:8080/exercises/56

###
POST http://localhost:8080/training
Accept: application/json
Content-Type: application/json

{
  "exerciseId": "1",
  "userId": "1",
  "reps": "12",
  "weight": "40"
}

###
GET http://localhost:8080/training/1/2022-07-20