POST http://localhost:8080/exercises/add
Accept: application/json
Content-Type: application/json

{
  "id": null,
  "exerciseName": "Klasyczny martwy ciąg",
  "engName": "Deadlift",
  "mainMuscleGroup": [
    "dwugłowy uda",
    "prostownik grzbietu"
  ],
  "supportMuscleGroup": [
    "pośladkowy",
    "czworogłowy uda",
    "czworoboczny lędźwi",
    "czworoboczny"
  ]
}


###
GET http://localhost:8080/exercises

###
GET http://localhost:8080/exercises/56

###
POST http://localhost:8080/training
Accept: application/json
Content-Type: application/json

{
  "exerciseId": "1",
  "userId": "1",
  "reps": "12",
  "weight": "60"
}

###
GET http://localhost:8080/training/1/2022-07-20