POST http://localhost:8080/exercises/add
Accept: application/json
Content-Type: application/json

{
  "name": "abc",
  "engName": "abc",
  "mainMuscleGroup": [
    "abc"
  ],
  "supportMuscleGroup": [
    "abc",
    "abc"
  ]
}

###
GET http://localhost:8080/exercises

###
GET http://localhost:8080/exercises/5

###
POST http://localhost:8080/training
Accept: application/json
Content-Type: application/json

{
  "exerciseId": "1",
  "userId": "1",
  "reps": "12",
  "weight": "40"
}

###
GET http://localhost:8080/training/5/fsdfsawe
//mockMvc.perform(MockMvcRequestBuilders.get("/training")
//
//.param("userId", "1L")
//.param("date", "2016-01-25T21:34:55"))
//.andDo(print())
//.andExpect(MockMvcResultMatchers.status().is(200));
//}