version: '3'
services:
  postgres:
    image: postgres:14.2-alpine
    ports:
      - "9000:5432"
    environment:
      - POSTGRES_DB=exercises
      - POSTGRES_USER=abc
      - POSTGRES_PASSWORD=abc
      - PGDATA=/data
    command: ["postgres", "-c", "log_statement=all"]
    # volumes:
    #  - ./data:/data
